name: trength
description: An elegant, minimalist workout tracking application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # UI Components
  fl_chart: ^0.65.0
  flutter_vector_icons: ^2.0.0
  lucide_icons_flutter: ^3.0.9
  flutter_svg: ^2.0.10

  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive Generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
     - assets/data/exercises.json
     - assets/icons/
     - assets/images/

  # Custom Quicksand font configuration
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.otf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.otf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.otf
          weight: 700
